### ISSUE TITLE
TODO: Better implementation of CSS Grid

### ISSUE THREAD

**Issue by necraidan** [necraidan/funkoPoop#4]
An example of what I want:

```scss
.content {
    margin: 2em;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-gap: 2em;
    justify-content: center;
}

@media screen and (max-width: 770px) {
    .content {
        grid-template-columns: repeat(1, 1fr);
    }
}

@media screen and (min-width: 770px) and (max-width: 1200px) {
    .content {
        grid-template-columns: repeat(2, 1fr);
    }
}
```
